### ISSUE TITLE
写入剪切板失败

### ISSUE THREAD

**Issue by Liu8Can** [jaywcjlove/wxmp#44]
网页版，转换完成后，点击复制按钮，并未能成功写入剪切板。
微信公众号排版编辑器v233

Google Chrome

版本 127.0.6533.73（正式版本） （64 位）

**Comment by jaywcjlove** [comment]
@Liu8Can 文章预览，全选 <kbd>command</kbd> + <kbd>c</kbd> 复制 我排查一下

**Comment by jaywcjlove** [comment]
@Liu8Can 问题已排除，js API 已过时的兼容问题，就使用最新的 API 吧

https://github.com/jaywcjlove/wxmp/blob/41eb86cd2b2e932bded6acf3a18f0de2a9e07901/website/src/commands/copy.tsx#L23

**Comment by jaywcjlove** [comment]
https://github.com/jaywcjlove/wxmp/blob/8991adcd15645d02a9923c2073955176775a3a4a/website/src/commands/copy.tsx#L22-L32

我测试过了没有问题可以复制的样子
